services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/test
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
